set(5500_srcs
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/5500/wizchip_ethnetif.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/5500/wizchip_test.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/5500/w5500/w5500.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/5500/wizchip_port.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/5500/wizchip_conf.c
    )

set(curl_srcs
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/c-hyper.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/socketpair.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_base64.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_rtmp.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/cf-haproxy.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/http_aws_sigv4.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_ntlm_wb.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/bufq.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/hostasyn.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/schannel_verify.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/sectransp.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/bearssl.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/gskit.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/mbedtls_threadlock.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/rustls.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/gtls.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/schannel.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/mbedtls.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/wolfssl.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/vtls.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/x509asn1.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/nss.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/keylog.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/hostcheck.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vtls/openssl.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/rename.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/strdup.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_md5.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/cf-socket.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/strerror.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/dict.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/cf-h1-proxy.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/url.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/escape.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/setopt.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/speedcheck.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/socks.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/parsedate.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/strtoofft.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/doh.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_path.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/connect.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/mprintf.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/easy.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/version_win32.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/llist.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/hostip.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/telnet.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/asyn-thread.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/gopher.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/netrc.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/rand.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/mime.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/transfer.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/http_ntlm.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/dynhds.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/content_encoding.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/amigaos.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/http2.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/altsvc.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/fopen.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/krb5_sspi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/cram.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/oauth2.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/spnego_gssapi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/vauth.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/spnego_sspi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/digest.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/cleartext.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/gsasl.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/krb5_gssapi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/ntlm_sspi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/ntlm.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vauth/digest_sspi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/system_win32.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/http1.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/http.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/easyoptions.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/tftp.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/smb.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/progress.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_ntlm_core.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/nonblock.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/ldap.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_sspi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/hostsyn.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/http_proxy.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/socks_sspi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/rtsp.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/cfilters.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/splay.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/strcase.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/http_chunks.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vssh/libssh2.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vssh/libssh.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vssh/wolfssh.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/hostip4.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/smtp.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/mqtt.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/ftp.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_sha256.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/pop3.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/psl.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/openldap.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/ws.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/select.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/timeval.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/getinfo.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/formdata.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/conncache.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/multi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_memrchr.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_des.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/memdebug.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/asyn-ares.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/cf-h2-proxy.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/sendf.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/bufref.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_endian.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/strtok.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/hmac.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/headers.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/krb5.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_md4.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/dynbuf.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_get_line.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/timediff.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_fnmatch.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_multibyte.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/pingpong.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/idn.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/slist.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_log.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/easygetopt.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/cf-https-connect.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/urlapi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/http_negotiate.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/fileinfo.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/hostip6.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_threads.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/file.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_sasl.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_range.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/inet_pton.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/ftplistparser.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/cookie.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_gssapi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/noproxy.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/getenv.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/inet_ntop.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/http_digest.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/imap.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/socks_gssapi.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/warnless.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/hsts.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_version.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_addrinfo.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/if2ip.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vquic/vquic.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vquic/curl_quiche.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vquic/curl_msh3.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/vquic/curl_ngtcp2.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/curl_gethostname.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/share.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/curl/curl-8.1.2/lib/hash.c
    )

set(http-parser_srcs
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/http-parser/http_parser.c
    )

set(lfs_srcs
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/lfs/lfs.c
    ${CMAKE_SOURCE_DIR}/ql_application/third_party/lfs/lfs_util.c
    )

set(example_srcs
    ${CMAKE_SOURCE_DIR}/ql_application/example/uart_demo/ql_uart_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/wlan_demo/ql_wlan_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/adc_demo/ql_adc_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/lowpower_demo/ql_lowpower_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/tls_demo/ql_tls_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/ble_demo/ql_ble_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/spi_flash_demo/ql_spi_flash_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/http_demo/ql_http_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/timer_demo/ql_timer_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/spi_demo/ql_spi_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/gpio_demo/ql_gpio_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/watchdog_demo/ql_watchdog_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/socket_demo/ql_socket_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/osi_demo/ql_osi_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/mqtt_demo/ql_mqtt_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/customer_cli/ql_customer_cli.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/pwm_demo/ql_pwm_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/i2c_eeprom_demo/ql_i2c_eeprom_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/ota_demo/ql_ota_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/flash_demo/ql_flash_demo.c
    ${CMAKE_SOURCE_DIR}/ql_application/example/wlan_config_network_demo/ql_wlan_config_network_demo.c
    )

