set(lwip_srcs
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/dhcpd/dhcp-server-main.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/dhcpd/dhcp-server.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/port/ethernetif.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/port/net.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/port/sys_arch.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/api/tcpip.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/api/api_lib.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/api/sockets.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/api/api_msg.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/api/netifapi.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/api/netdb.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/api/netbuf.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/api/err.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/inet_chksum.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/dns.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/tcp_in.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/pbuf.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/mem.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/timeouts.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/memp.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ip.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/tcp_out.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/netif.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv4/icmp.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv4/ip4_frag.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv4/ip4_addr.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv4/etharp.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv4/igmp.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv4/dhcp.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv4/ip4.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/sys.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/def.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/udp.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/raw.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/init.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/stats.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/tcp.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv6/ethip6.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv6/inet6.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv6/ip6_frag.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv6/nd6.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv6/dhcp6.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv6/mld6.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv6/icmp6.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv6/ip6.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/core/ipv6/ip6_addr.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/netif/slipif.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/netif/lowpan6.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/netif/ethernet.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/netif/ethernetif.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/apps/ping/ping.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/apps/httpd/fs.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/lwip_intf/lwip-2.0.2/src/apps/httpd/httpd.c
    )

set(mbedtls_srcs
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/x509write_crt.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/nist_kw.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ecdsa.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/pk_wrap.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto_se.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/entropy.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/x509_csr.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ssl_tls.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ecdh.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/camellia.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/poly1305.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto_hash.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/havege.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/error.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/entropy_poll.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/x509write_csr.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/x509_crt.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/md2.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/pk.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/rsa.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto_ecp.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/sha512.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ecp_curves.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ecjpake.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/arc4.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/mps_trace.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/asn1write.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/cipher.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/x509_crl.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/bignum.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/hmac_drbg.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/pkcs11.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/pkwrite.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ssl_msg.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/aes.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/cipher_wrap.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ctr_drbg.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ssl_ticket.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/x509_create.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/base64.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/gcm.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/padlock.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/blowfish.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto_rsa.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/hkdf.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ripemd160.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto_client.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/md4.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/version.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/net_sockets.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/timing.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto_mac.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/md.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/pkcs5.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/platform.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/pkcs12.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto_cipher.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/pem.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/chacha20.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/md5.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/rsa_internal.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/memory_buffer_alloc.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/threading.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/chachapoly.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto_driver_wrappers.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/oid.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ccm.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/aria.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ssl_tls13_keys.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ecp.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ssl_cli.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/xtea.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto_aead.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/version_features.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/aesni.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/cmac.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_its_file.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ssl_srv.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/x509.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/des.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/mps_reader.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/certs.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ssl_ciphersuites.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/constant_time.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/asn1parse.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto_storage.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/psa_crypto_slot_management.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/sha256.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/platform_util.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/sha1.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ssl_cache.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/dhm.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/pkparse.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/ssl_cookie.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls/library/debug.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/esp_ssl_cli.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/tls_client.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/timing_alt.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/tls_certificate.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/esp_mbedtls_dynamic_impl.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/esp_ssl_srv.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/esp_ssl_tls.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/ecp_alt.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/tls_net.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/ecp_curves_alt.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/tls_hardware.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls-port/src/tls_mem.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/mbedtls/mbedtls_ui/sl_tls.c
    )

set(mqtt_srcs
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/client/src/MQTTFreeRTOS.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/client/src/MQTTClient.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/packet/src/MQTTSerializePublish.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/packet/src/MQTTPacket.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/packet/src/MQTTSubscribeServer.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/packet/src/MQTTConnectClient.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/packet/src/MQTTFormat.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/packet/src/MQTTConnectServer.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/packet/src/MQTTUnsubscribeServer.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/packet/src/MQTTDeserializePublish.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/packet/src/MQTTSubscribeClient.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/packet/src/MQTTUnsubscribeClient.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/mqtt_ui/mqtt_client_com_port.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/mqtt_ui/tcp_mqtt/tcp_mqtt_client_port.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/mqtt_ui/mqtt_client_core.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/mqtt_ui/ssl_mqtt/ssl_mqtt_client_port.c
    ${CMAKE_SOURCE_DIR}/ql_components/third_party/paho-mqtt/client/paho_mqtt_udp.c
    )

